### ISSUE TITLE
The application is using the default 500 color code.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager-rest-api#13]
We have to make API like whatever colour code we have set it will set at 500.

https://github.com/wpeventmanager/wp-event-manager-organizer-app/issues/152

**Comment by hiteshmakvana** [comment]
If i will do 500 as a primary color or the main color then the shade of the color will be incorrect.

**Comment by krinaydhanani** [comment]
Yes now, this issue was fixed. Now the APK is using 500 code.
