### ISSUE TITLE
Need to fix Issue- Check validation for all fields

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager-rest-api#18]
API Access - 

When I have not filled details and click on the"Generate API key" button then validation is not check for fields.

Here add proper validation message.

![image](https://user-images.githubusercontent.com/75515088/107344948-10665c00-6ae9-11eb-96e4-166bb094c260.png)

**Comment by hiteshmakvana** [comment]
It's not required and it is not used in api authentication anywhere.

**Comment by krinaydhanani** [comment]
I think we should put the validation in this form but according to @hiteshmakvana we not need to show this. I still disagree with this decision.
