### ISSUE TITLE
Need to fix issue - Save or Update message should display on the screen

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager-rest-api#19]
General setting 

When I have add new details /update details then Save or Update message should display on the screen.

So user can understand.

![image](https://user-images.githubusercontent.com/75515088/107347106-79e76a00-6aeb-11eb-92ae-3f6bb6aecc29.png)

**Comment by hiteshmakvana** [comment]
Save is done with page load so no need to do show message.

**Comment by krinaydhanani** [comment]
I disagree with this decision. We should show the setting with loader notice once the user saves the setting but, according to @hiteshmakvana page load after saving so no need to do show the message.
