### ISSUE TITLE
Need to fix the loader issue in Rest API.

### ISSUE THREAD

**Issue by krinaydhanani** [wpeventmanager/wp-event-manager-rest-api#7]
Need to fix the loader issue in Rest API.

![image](https://user-images.githubusercontent.com/35419531/104990872-84aa6400-5a43-11eb-8c2c-d6642e6426ab.png)

**Comment by hiteshmakvana** [comment]
Now the whole structure is changed. Can you please provide which loader you are referring to?

**Comment by krinaydhanani** [comment]
Yes, now loading is perfect. I need more improvement.
